name: Bonus Workflow

on: [push]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Setup Java JDK
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4.7.0
          with:
            distribution: 'corretto'
            java-version: '8'
        - run: pwd && ls -la
        - run: mvn -version

        - name: List files
          run: ls -la

        - name: Read file
          run: cat README.md