name: Bonus Workflow

on: [push]

jobs:
    checkout_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

    mvn_build:
        needs: checkout_job
        runs-on: ubuntu-latest
        steps:
        - name: Setup JDK
          uses: actions/setup-java@v4.7.0
          with:
            distribution: 'corretto'
            java-version: '8'

        - name: MVN Compie
          run: |
            pwd
            ls -la
            mvn clean compile
    mvn_test:
        runs-on: ubuntu-latest
        needs: mvn_build
        steps:
        - name: Setup JDK
          uses: actions/setup-java@v4.7.0
          with:
            distribution: 'corretto'
            java-version: '8'

        - name: MVN Test
          run: |
            pwd
            ls -la
            mvn test
