name: Bonus Workflow

on: [push]

jobs:
    checkout_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

    mvn_job:
        runs-on: ubuntu-latest
        steps:
        - name: MVN Install
          uses: actions/setup-java@v4.7.0
          with:
            distribution: 'corretto'
            java-version: '8'

        - name: MVN Check
          run: |
            pwd
            ls -la
            mvn clean install
